### PR TITLE
Fix bugs that were preventing state machine deployment

### LINKED ISSUE #58: Bugs in `generateStateMachineParams.js` that prevents state machine from deploying
Usually during deployment there is a "Successfully created state machine" message logged to the console but this message is not appearing.

There are two bugs in the `generateStateMachineParams.js` file that prevent the state machine from deploying. The failure is happening silently upon deployment, and then an exception is thrown at teardown stating that the state machine ARN is undefined (because it was never deployed).

### PR DESCRIPTION
**Pull request by zklamm**
Fixes #58.

### CODE REVIEW

File: src/aws/step-function/generateStateMachineParams.js [hunk 1]
```diff
@@ -18,13 +18,13 @@ const readStateMachineDefinition = () => {
...
-  const { region, accountNumber } = readConfigFileFromHome(accountInfoPath);
+  const { accountNumber, region } = readConfigFileFromHome(accountInfoPath);
   let modifiedDefinition = definition;
 
   modifiedDefinition = modifiedDefinition.replace(/REGION/g, region);
   modifiedDefinition = modifiedDefinition.replace(
     /ACCOUNT_ID/g,
-    account_number
+    accountNumber
   );
```
Comment (johnisom) [inline src/aws/step-function/generateStateMachineParams.js:28]: Good catch
