### PR TITLE
Fix bug concerning the obfuscate function

### LINKED ISSUE #70: `maestro config` is failing due to `undefined` being passed where a string expected in `obfuscate.js`
`maestro config` is failing when run without an existing account info file. This is because obfuscate is expecting a string but is receiving undefined since there is no file to read. The length method is being called on undefined, throwing an error.

### PR DESCRIPTION
**Pull request by zklamm**
Fixes #70 

I fixed the bug created by `obfuscate.js` as well as extracted out some common logic to a couple of new functions.

### CODE REVIEW

File: src/commands/config.js [hunk 1]
```diff
@@ -14,40 +15,44 @@ const createHiddenMaestroDir = () => {
...
 };
 
+const getAcctNum = async () => {
+  const promptMsg = "Please enter your AWS Account Number";
+
+  if (existingAccountNum) {
+    return await promptAsync(promptMsg, obfuscate(existingAccountNum, 4));
+  } else {
+    return await promptAsync(promptMsg);
+  }
```
Comment (johnisom) [inline src/commands/config.js:25]: Good idea

File: src/commands/config.js [hunk 2]
```diff
@@ -14,40 +15,44 @@ const createHiddenMaestroDir = () => {
...
 };
 
+const getRegion = async () => {
+  const promptMsg = "Please enter the region for your AWS services";
+
+  if (existingRegion) {
+    return await promptAsync(promptMsg, existingRegion);
+  } else {
+    return await promptAsync(promptMsg);
+  }
```
Comment (johnisom) [inline src/commands/config.js:47]: Good idea
